name: Trigger auto deployment for container-app-s64g6bhlb2am6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-s64g6bhlb2am6-AutoDeployTrigger-dd88a5e9-7ec5-445d-b926-ae8491c003e7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPS64G6BHLB2AM6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPS64G6BHLB2AM6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPS64G6BHLB2AM6_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPS64G6BHLB2AM6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPS64G6BHLB2AM6_REGISTRY_PASSWORD }}
          containerAppName: container-app-s64g6bhlb2am6
          resourceGroup: todonodejspgsqlgoogleauth835784c6
          imageToBuild: default/container-app-s64g6bhlb2am6:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


